### ISSUE TITLE
I need a solid junior to fix this crap for me

### ISSUE THREAD

**Issue by steveoo-tech** [steveoo-tech/honeybooboo#2]
Hey junior, time to get your fingers twiddling! I need you to change the grocery list and add some stuff that you can't find at the grocery store..don't ask why I want this done..just get it done juni

**Comment by RTeeen** [comment]
EZ Peasy cheesy

**Comment by steveoo-tech** [comment]
This issue has been solved @RTeeen, good work on this one!
