### ISSUE TITLE
**Create an E-transfer system**

### ISSUE THREAD

**Issue by RTeeen** [steveoo-tech/honeybooboo#6]
I was thinking about adding an E-transfer function to your app. I t will be easier to do these serious money transfers.
Let me know when I can start on this.

**Comment by steveoo-tech** [comment]
I'd love a PR to solve this

**Comment by RTeeen** [comment]
You got it!

**Comment by steveoo-tech** [comment]
Thanks @RTeeen  for the grade A security. You gave us great security and with great security comes great responsibilities. It's great people like you that make our nation so strong. thankyou goodsir
Issue #6 Resolved
